sonar.projectKey=boubli_AMUD-Dashboard
sonar.organization=boubli
sonar.sources=amud-server/src,amud-agent/src,amud-protocol/src,ui
sonar.exclusions=**/target/**,**/ui/static/logos/**,**/docs/**,**/*.svg,scripts/**
sonar.tests=amud-server/tests
