sonar.projectKey=boubli_AMUD-Dashboard
sonar.organization=boubli
sonar.sources=amud-server/src,amud-agent/src,amud-protocol/src,ui
sonar.exclusions=**/target/**,**/ui/static/logos/**,**/docs/**,**/*.svg,maintainer-local/**,maintainer-local.example/**,**/ui/static/themes/icons/**,**/ui/static/themes/previews/**,**/ui/static/themes/wallpapers/**
sonar.cpd.exclusions=**/ui/static/themes/*.css,**/ui/static/theme-layouts/*.css
sonar.tests=amud-server/tests
